locustfile = benchmarking/DGGRS_IGEO7_Zarr_provider/DGGRS_IGEO7_Zarr_provider.py
headless = true
host = http://127.0.0.1:8000
users = 5
spawn-rate = 10
run-time = 1m
html = benchmarking/DGGRS_IGEO7_Zarr_provider/locust.html
